const letters = [
    'GATO',
    'ARGENTINA',
    'ZAPATO',
    'ALBA',
    'DINOSAURIO',
    'MOCHILA',
    'CUADRADO',
    'ÑOQUIS',
    'OMAR',
    'AHORCADO',
    'CHORIPAN',
    'ASINCRONISMO',
    'PROMESAS',
];